version: '3'

services:
    web:
        image: nginx:latest
        depends_on:
          - php
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        volumes:
            - ./code:/code
        networks:
            - code-network
    mariadb:
        container_name: dockerbasic_mariadb_1
        image: mariadb:latest
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_USER: hackathon
            MYSQL_PASSWORD: hackathon
            MYSQL_DATABASE: hackathon
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysqldata:/docker-entrypoint-initdb.d
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
